export const metadata = {
  title: "Privacy Policy — HomeRenovAi",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen">
      {/* Spacer to push content below fixed header */}
      <div className="h-24 md:h-32"></div>

      <div className="mx-auto max-w-4xl px-6 pb-24 md:px-8">
        <header className="mb-12">
          <div className="inline-flex items-center gap-2 rounded-full border border-[#D4AF37]/30 bg-[#D4AF37]/10 px-4 py-1.5 mb-6">
            <span className="h-2 w-2 rounded-full bg-[#D4AF37] animate-pulse" />
            <span className="text-xs font-semibold tracking-widest text-[#D4AF37] uppercase">Legal Information</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-serif text-black dark:text-white mb-4">Privacy Policy</h1>
          <p className="text-zinc-500 dark:text-zinc-400">
            Last updated: March 2026
          </p>
        </header>

        <div className="prose prose-zinc dark:prose-invert max-w-none prose-headings:font-serif prose-headings:font-normal prose-h2:text-3xl prose-h2:mt-12 prose-h2:mb-6 prose-p:leading-relaxed prose-p:text-zinc-600 dark:prose-p:text-zinc-300">
          <p className="text-lg">
            At <strong>HomeRenovAi</strong>, we take your privacy seriously. This Privacy Policy describes how we collect, use,
            store, and protect your personal data when you use our artificial intelligence interior and exterior design application.
          </p>

          <h2>1. Information We Collect</h2>
          <p>
            To provide you with our design generation services, we collect and process the following types of information:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-zinc-600 dark:text-zinc-300">
            <li><strong>Account Data:</strong> When you register via email or Google OAuth, we collect basic profile information including your email address, name (if provided), and an authentication profile picture.</li>
            <li><strong>User Content:</strong> Images or photos of environments and facades that you upload to our platform ("Original Images") to be processed by our AI algorithms.</li>
            <li><strong>Generated Designs:</strong> The interior and exterior designs generated by the Artificial Intelligence ("Generated Images") based on your inputs and prompts.</li>
            <li><strong>Payment Information:</strong> When upgrading to Premium plans, billing details are processed directly by our payment gateway (Stripe). We do not store full credit card numbers on our servers.</li>
          </ul>

          <h2>2. How We Use Your Information</h2>
          <p>
            Your information is strictly used to deliver, maintain, and improve the <strong>HomeRenovAi</strong> experience:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-zinc-600 dark:text-zinc-300">
            <li><strong>Core Service:</strong> To process your uploaded photos through our AI engine and generate the requested architectural styles.</li>
            <li><strong>Account Management:</strong> To maintain your personal gallery, manage your credit balances (Free, Bonus, or Paid), and process subscription renewals.</li>
            <li><strong>Communication:</strong> To send essential transactional emails (like welcome emails, password resets, and payment receipts) and respond to support inquiries.</li>
            <li><strong>System Integrity:</strong> To monitor for abuse, enforce our Terms of Service, and ensure the security of our infrastructure.</li>
          </ul>

          <h2>3. Artificial Intelligence and Your Images</h2>
          <p>
            <strong>HomeRenovAi</strong> uses advanced generative AI models.
          </p>
          <div className="bg-zinc-100 dark:bg-zinc-900/50 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-6 my-6">
            <ul className="list-none space-y-3 m-0 p-0 text-zinc-600 dark:text-zinc-300">
              <li className="flex gap-3"><span className="text-[#D4AF37]">✦</span> <strong>No Model Training:</strong> The photos you upload are <em>not</em> used to train, retrain, or improve our core foundation models or those of our third-party AI partners.</li>
              <li className="flex gap-3"><span className="text-[#D4AF37]">✦</span> <strong>Ephemeral Processing:</strong> Your images are processed securely and deleted from GPU memory immediately after the design generation is completed.</li>
              <li className="flex gap-3"><span className="text-[#D4AF37]">✦</span> <strong>Private Gallery:</strong> The inputs and generated results are stored in your secure, private Supabase cloud storage bucket and are visible only to you.</li>
            </ul>
          </div>

          <h2>4. Data Sharing and Third-Party Providers</h2>
          <p>
            We do not sell, rent, or trade your personal information to third parties. We only share necessary data with trusted infrastructure providers who operate under strict confidentiality agreements:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-zinc-600 dark:text-zinc-300">
            <li><strong>Supabase:</strong> For secure database hosting, user authentication, and cloud storage of your gallery images.</li>
            <li><strong>Stripe:</strong> For secure processing of subscriptions, payments, and billing events.</li>
            <li><strong>fal.ai:</strong> Strictly for the transient processing of image-to-image generation requests.</li>
            <li><strong>Resend:</strong> For the delivery of transactional emails to your inbox.</li>
          </ul>

          <h2>5. Data Retention and Deletion</h2>
          <p>
            We retain your personal information, uploaded images, and generated designs only for as long as your account remains active.
          </p>
          <p>
            <strong>Your right to delete:</strong> You have full control over your data. You can delete individual designs directly within your Gallery. If you wish to completely close your account and permanently erase all associated data, including your profile, remaining credits, and whole image history, please contact our support team. Upon verification, your data will be permanently purged from our active databases and storage buckets within 30 days.
          </p>

          <h2>6. Security Measures</h2>
          <p>
            We deploy strict security protocols to protect your information, including end-to-end encryption for AI generation payloads, Row Level Security (RLS) on our databases ensures one user cannot access another's gallery, and token-based authentication via Supabase Auth.
          </p>

          <h2>7. Contact Us</h2>
          <p>
            If you have any questions, concerns, or requests regarding this Privacy Policy or how your data is handled, please reach out to us at:
          </p>
          <p className="font-medium text-black dark:text-white mt-4">
            💌 hello@homerenovai.com
          </p>
        </div>
      </div>
    </main>
  );
}
