import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | HomeRenovAi",
  description:
    "Read the Terms of Service for using HomeRenovAi's AI-powered interior and exterior design platform.",
  keywords:
    "HomeRenovAi terms, terms of service, user agreement, AI design terms, service conditions",
  openGraph: {
    title: "Terms of Service | HomeRenovAi",
    description:
      "Read the Terms of Service for using HomeRenovAi's AI-powered interior and exterior design platform.",
    url: "https://homerenovai.com/terms",
    siteName: "HomeRenovAi",
    images: [
      {
        url: "https://homerenovai.com/OG_1200x630_.jpg",
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Terms of Service | HomeRenovAi",
    description:
      "Read the Terms of Service for using HomeRenovAi's AI-powered interior and exterior design platform.",
    images: ["https://homerenovai.com/OG_1200x630_.jpg"],
  },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen">
      {/* Spacer to push content below fixed header */}
      <div className="h-24 md:h-32"></div>

      <div className="mx-auto max-w-4xl px-6 pb-24 md:px-8">
        <header className="mb-12">
          <div className="inline-flex items-center gap-2 rounded-full border border-[#D4AF37]/30 bg-[#D4AF37]/10 px-4 py-1.5 mb-6">
            <span className="h-2 w-2 rounded-full bg-[#D4AF37] animate-pulse" />
            <span className="text-xs font-semibold tracking-widest text-[#D4AF37] uppercase">Legal Information</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-serif text-black dark:text-white mb-4">Terms of Service</h1>
          <p className="text-zinc-500 dark:text-zinc-400">
            Last updated: March 2026
          </p>
        </header>

        <div className="prose prose-zinc dark:prose-invert max-w-none prose-headings:font-serif prose-headings:font-normal prose-h2:text-3xl prose-h2:mt-12 prose-h2:mb-6 prose-p:leading-relaxed prose-p:text-zinc-600 dark:prose-p:text-zinc-300">
          <p className="text-lg">
            Welcome to <strong>HomeRenovAi</strong>. These Terms of Service (&quot;Terms&quot;) govern your access to and use of the
            HomeRenovAi platform, including our website, AI-powered design generation services, and all related features
            (collectively, the &quot;Service&quot;). By creating an account or using the Service, you agree to be bound by these Terms.
          </p>

          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using <strong>HomeRenovAi</strong>, you confirm that you are at least 18 years old and have the legal
            capacity to enter into these Terms. If you are using the Service on behalf of an organization, you represent that you
            have the authority to bind that organization to these Terms. If you do not agree with any part of these Terms, you
            must immediately discontinue use of the Service.
          </p>

          <h2>2. Description of the Service</h2>
          <p>
            <strong>HomeRenovAi</strong> is an artificial intelligence application that transforms photos of interior and exterior
            environments into new architectural and design concepts. Users upload images and select desired styles, and the platform
            generates AI-rendered designs based on the input.
          </p>
          <div className="bg-zinc-100 dark:bg-zinc-900/50 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-6 my-6">
            <ul className="list-none space-y-3 m-0 p-0 text-zinc-600 dark:text-zinc-300">
              <li className="flex gap-3"><span className="text-[#D4AF37]">✦</span> <strong>AI Generation:</strong> Results are generated by artificial intelligence models and may vary in accuracy, style fidelity, and photorealism. Generated images are intended for inspiration and visualization purposes.</li>
              <li className="flex gap-3"><span className="text-[#D4AF37]">✦</span> <strong>No Guarantee:</strong> We do not guarantee that the Service will meet your specific expectations, that any particular design outcome will be achieved, or that the platform will be available without interruption.</li>
              <li className="flex gap-3"><span className="text-[#D4AF37]">✦</span> <strong>Continuous Improvement:</strong> We reserve the right to modify, update, or discontinue features of the Service at any time to improve the user experience and overall quality.</li>
            </ul>
          </div>

          <h2>3. User Accounts</h2>
          <p>
            To access the full functionality of <strong>HomeRenovAi</strong>, you must register for an account using a valid email
            address or through Google OAuth. You are responsible for:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-zinc-600 dark:text-zinc-300">
            <li>Maintaining the confidentiality of your login credentials and not sharing your account with third parties.</li>
            <li>All activity that occurs under your account, whether or not authorized by you.</li>
            <li>Ensuring that the information provided during registration is accurate and up to date.</li>
          </ul>
          <p>
            We reserve the right to suspend or terminate accounts that violate these Terms and exhibit fraudulent behavior at our sole discretion.
          </p>

          <h2>4. Credits, Subscriptions, and Payments</h2>
          <p>
            <strong>HomeRenovAi</strong> operates on a credit-based system. Each AI design generation consumes credits from your
            account balance.
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-zinc-600 dark:text-zinc-300">
            <li><strong>Free Credits:</strong> New users may receive a limited number of complimentary credits upon registration. These credits are non-transferable and may be subject to expiration.</li>
            <li><strong>Bonus Credits:</strong> Promotional credits may be granted at our discretion. These credits cannot be exchanged for monetary value.</li>
            <li><strong>Premium Subscriptions:</strong> Paid plans provide recurring credit allocations and access to enhanced features. Subscriptions are billed periodically through <strong>Paddle</strong>, our secure payment processor.</li>
            <li><strong>Cancellation:</strong> You may cancel your subscription at any time through the customer portal. Upon cancellation, your subscription remains active until the end of the current billing cycle. No prorated refunds are issued for partial billing periods.</li>
            <li><strong>Refund Policy:</strong> Due to the nature of AI processing costs, credits that have already been consumed are non-refundable. Refund requests for unused credits or billing issues will be evaluated on a case-by-case basis by contacting our support team.</li>
          </ul>

          <h2>5. Acceptable Use</h2>
          <p>
            You agree to use <strong>HomeRenovAi</strong> responsibly and in compliance with all applicable laws. The following
            activities are strictly prohibited:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-zinc-600 dark:text-zinc-300">
            <li>Uploading content that is illegal, obscene, defamatory, threatening, or that infringes on the intellectual property or privacy rights of third parties.</li>
            <li>Attempting to reverse-engineer, decompile, or extract the source code, algorithms, or AI models used by the Service.</li>
            <li>Using automated scripts, bots, or scrapers to access or interact with the Service without prior written authorization.</li>
            <li>Circumventing, disabling, or interfering with any security features, usage limits, or access controls of the platform.</li>
            <li>Reselling, redistributing, or sublicensing the Service or generated content for commercial purposes without authorization.</li>
          </ul>
          <p>
            Violation of these terms may result in immediate suspension or permanent termination of your account without prior notice.
          </p>

          <h2>6. Intellectual Property</h2>
          <p>
            All intellectual property related to the <strong>HomeRenovAi</strong> platform — including but not limited to the
            brand name, logos, software, user interface design, AI models, and proprietary algorithms — is the exclusive
            property of HomeRenovAi and is protected by applicable copyright, trademark, and intellectual property laws.
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-zinc-600 dark:text-zinc-300">
            <li><strong>Your Content:</strong> You retain full ownership of the original images you upload. By uploading content, you grant HomeRenovAi a limited, non-exclusive license to process those images solely for the purpose of generating your requested designs.</li>
            <li><strong>Generated Designs:</strong> You are granted a personal, non-exclusive license to use, download, and share the AI-generated designs for personal, non-commercial purposes. Commercial use of generated images may require a separate licensing agreement.</li>
          </ul>

          <h2>7. Limitation of Liability</h2>
          <p>
            The Service is provided on an <strong>&quot;as is&quot;</strong> and <strong>&quot;as available&quot;</strong> basis,
            without warranties of any kind, whether express, implied, or statutory. To the fullest extent permitted by applicable law:
          </p>
          <div className="bg-zinc-100 dark:bg-zinc-900/50 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-6 my-6">
            <ul className="list-none space-y-3 m-0 p-0 text-zinc-600 dark:text-zinc-300">
              <li className="flex gap-3"><span className="text-[#D4AF37]">✦</span> HomeRenovAi shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of your use of, or inability to use, the Service.</li>
              <li className="flex gap-3"><span className="text-[#D4AF37]">✦</span> We are not responsible for any decisions made based on AI-generated designs, including architectural, renovation, or decoration decisions.</li>
              <li className="flex gap-3"><span className="text-[#D4AF37]">✦</span> Our total aggregate liability for any claims arising from the Service shall not exceed the amount you have paid to HomeRenovAi in the twelve (12) months preceding the claim.</li>
            </ul>
          </div>

          <h2>8. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless <strong>HomeRenovAi</strong>, its founders, employees, and
            service providers from any claims, damages, losses, liabilities, and expenses (including reasonable attorney fees)
            arising from your use of the Service, your violation of these Terms, or your infringement of any third-party rights.
          </p>

          <h2>9. Modifications to the Terms</h2>
          <p>
            We reserve the right to update or modify these Terms at any time. When we do, the &quot;Last updated&quot; date at the top of
            this page will be revised. Continued use of the Service after any such changes constitutes your acceptance of the
            updated Terms. We encourage you to review this page periodically.
          </p>

          <h2>10. Termination</h2>
          <p>
            We may suspend or terminate your access to the Service at any time, with or without cause, and with or without notice.
            Upon termination:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-zinc-600 dark:text-zinc-300">
            <li>Your right to use the Service ceases immediately.</li>
            <li>Any remaining credits in your account are forfeited and non-refundable.</li>
            <li>We may delete your account data, including uploaded images and generated designs, in accordance with our Privacy Policy.</li>
          </ul>

          <h2>11. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with applicable laws. Any disputes arising out of or in
            connection with these Terms or the Service shall be resolved through good-faith negotiation. If a resolution cannot be
            reached, the dispute shall be submitted to the competent jurisdiction.
          </p>

          <h2>12. Contact Us</h2>
          <p>
            If you have any questions, concerns, or feedback regarding these Terms of Service, please reach out to us at:
          </p>
          <p className="font-medium text-black dark:text-white mt-4">
            💌 hello@homerenovai.com
          </p>
        </div>
      </div>
    </main>
  );
}
